spring.application.name=backend
# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/onboarding_db

# JWT
jwt.secret=ThisIsAVeryLongSecretKeyForJWTThatMustBeAtLeast256BitsLong!
jwt.expiration=3600000

# Mail (using Gmail SMTP ? replace with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onboardingsender25@gmail.com
spring.mail.password=jcmcazmmkavnaxhk
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App base URL (for activation link)
app.frontend.url=http://localhost:5173